//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YanSoft.CurrencyExchanger.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YanSoft.CurrencyExchanger.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE Dirham.
        /// </summary>
        internal static string Currency_AED {
            get {
                return ResourceManager.GetString("Currency_AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghan Afghani.
        /// </summary>
        internal static string Currency_AFN {
            get {
                return ResourceManager.GetString("Currency_AFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian Lek.
        /// </summary>
        internal static string Currency_ALL {
            get {
                return ResourceManager.GetString("Currency_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian Dram.
        /// </summary>
        internal static string Currency_AMD {
            get {
                return ResourceManager.GetString("Currency_AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands Antillean Gulden.
        /// </summary>
        internal static string Currency_ANG {
            get {
                return ResourceManager.GetString("Currency_ANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angolan Kwanza.
        /// </summary>
        internal static string Currency_AOA {
            get {
                return ResourceManager.GetString("Currency_AOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentine Peso.
        /// </summary>
        internal static string Currency_ARS {
            get {
                return ResourceManager.GetString("Currency_ARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian Dollar.
        /// </summary>
        internal static string Currency_AUD {
            get {
                return ResourceManager.GetString("Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba Florin.
        /// </summary>
        internal static string Currency_AWG {
            get {
                return ResourceManager.GetString("Currency_AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani Manat.
        /// </summary>
        internal static string Currency_AZN {
            get {
                return ResourceManager.GetString("Currency_AZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia And Herzegovina Konvertibilna Marka.
        /// </summary>
        internal static string Currency_BAM {
            get {
                return ResourceManager.GetString("Currency_BAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbados Dollar.
        /// </summary>
        internal static string Currency_BBD {
            get {
                return ResourceManager.GetString("Currency_BBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladesh Taka.
        /// </summary>
        internal static string Currency_BDT {
            get {
                return ResourceManager.GetString("Currency_BDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian Lev.
        /// </summary>
        internal static string Currency_BGN {
            get {
                return ResourceManager.GetString("Currency_BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahraini Dinar.
        /// </summary>
        internal static string Currency_BHD {
            get {
                return ResourceManager.GetString("Currency_BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundi Franc.
        /// </summary>
        internal static string Currency_BIF {
            get {
                return ResourceManager.GetString("Currency_BIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bermuda Dollar.
        /// </summary>
        internal static string Currency_BMD {
            get {
                return ResourceManager.GetString("Currency_BMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brunei Dollar.
        /// </summary>
        internal static string Currency_BND {
            get {
                return ResourceManager.GetString("Currency_BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivian Boliviano.
        /// </summary>
        internal static string Currency_BOB {
            get {
                return ResourceManager.GetString("Currency_BOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian Real.
        /// </summary>
        internal static string Currency_BRL {
            get {
                return ResourceManager.GetString("Currency_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamian Dollar.
        /// </summary>
        internal static string Currency_BSD {
            get {
                return ResourceManager.GetString("Currency_BSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin.
        /// </summary>
        internal static string Currency_BTC {
            get {
                return ResourceManager.GetString("Currency_BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutan Ngultrum.
        /// </summary>
        internal static string Currency_BTN {
            get {
                return ResourceManager.GetString("Currency_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botswana Pula.
        /// </summary>
        internal static string Currency_BWP {
            get {
                return ResourceManager.GetString("Currency_BWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Belarusian Ruble.
        /// </summary>
        internal static string Currency_BYN {
            get {
                return ResourceManager.GetString("Currency_BYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus Ruble.
        /// </summary>
        internal static string Currency_BYR {
            get {
                return ResourceManager.GetString("Currency_BYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belize Dollar.
        /// </summary>
        internal static string Currency_BZD {
            get {
                return ResourceManager.GetString("Currency_BZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Dollar.
        /// </summary>
        internal static string Currency_CAD {
            get {
                return ResourceManager.GetString("Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congolese Franc.
        /// </summary>
        internal static string Currency_CDF {
            get {
                return ResourceManager.GetString("Currency_CDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss Franc.
        /// </summary>
        internal static string Currency_CHF {
            get {
                return ResourceManager.GetString("Currency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilean Peso.
        /// </summary>
        internal static string Currency_CLP {
            get {
                return ResourceManager.GetString("Currency_CLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Yuan.
        /// </summary>
        internal static string Currency_CNY {
            get {
                return ResourceManager.GetString("Currency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombian Peso.
        /// </summary>
        internal static string Currency_COP {
            get {
                return ResourceManager.GetString("Currency_COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rica Colon.
        /// </summary>
        internal static string Currency_CRC {
            get {
                return ResourceManager.GetString("Currency_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuban Peso.
        /// </summary>
        internal static string Currency_CUP {
            get {
                return ResourceManager.GetString("Currency_CUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cape Verde Escudo.
        /// </summary>
        internal static string Currency_CVE {
            get {
                return ResourceManager.GetString("Currency_CVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Koruna.
        /// </summary>
        internal static string Currency_CZK {
            get {
                return ResourceManager.GetString("Currency_CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijibouti Franc.
        /// </summary>
        internal static string Currency_DJF {
            get {
                return ResourceManager.GetString("Currency_DJF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Krone.
        /// </summary>
        internal static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Peso.
        /// </summary>
        internal static string Currency_DOP {
            get {
                return ResourceManager.GetString("Currency_DOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algerian Dinar.
        /// </summary>
        internal static string Currency_DZD {
            get {
                return ResourceManager.GetString("Currency_DZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian Pound.
        /// </summary>
        internal static string Currency_EGP {
            get {
                return ResourceManager.GetString("Currency_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eritrea Nakfa.
        /// </summary>
        internal static string Currency_ERN {
            get {
                return ResourceManager.GetString("Currency_ERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopian Birr.
        /// </summary>
        internal static string Currency_ETB {
            get {
                return ResourceManager.GetString("Currency_ETB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiji Dollar.
        /// </summary>
        internal static string Currency_FJD {
            get {
                return ResourceManager.GetString("Currency_FJD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falkland Islands Pound.
        /// </summary>
        internal static string Currency_FKP {
            get {
                return ResourceManager.GetString("Currency_FKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Pound.
        /// </summary>
        internal static string Currency_GBP {
            get {
                return ResourceManager.GetString("Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian Lari.
        /// </summary>
        internal static string Currency_GEL {
            get {
                return ResourceManager.GetString("Currency_GEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghanaian Cedi.
        /// </summary>
        internal static string Currency_GHS {
            get {
                return ResourceManager.GetString("Currency_GHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibraltar Pound.
        /// </summary>
        internal static string Currency_GIP {
            get {
                return ResourceManager.GetString("Currency_GIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambian Dalasi.
        /// </summary>
        internal static string Currency_GMD {
            get {
                return ResourceManager.GetString("Currency_GMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea Franc.
        /// </summary>
        internal static string Currency_GNF {
            get {
                return ResourceManager.GetString("Currency_GNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala Quetzal.
        /// </summary>
        internal static string Currency_GTQ {
            get {
                return ResourceManager.GetString("Currency_GTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyana Dollar.
        /// </summary>
        internal static string Currency_GYD {
            get {
                return ResourceManager.GetString("Currency_GYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong Dollar.
        /// </summary>
        internal static string Currency_HKD {
            get {
                return ResourceManager.GetString("Currency_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduras Lempira.
        /// </summary>
        internal static string Currency_HNL {
            get {
                return ResourceManager.GetString("Currency_HNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian Kuna.
        /// </summary>
        internal static string Currency_HRK {
            get {
                return ResourceManager.GetString("Currency_HRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haiti Gourde.
        /// </summary>
        internal static string Currency_HTG {
            get {
                return ResourceManager.GetString("Currency_HTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian Forint.
        /// </summary>
        internal static string Currency_HUF {
            get {
                return ResourceManager.GetString("Currency_HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian Rupiah.
        /// </summary>
        internal static string Currency_IDR {
            get {
                return ResourceManager.GetString("Currency_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israeli Shekel.
        /// </summary>
        internal static string Currency_ILS {
            get {
                return ResourceManager.GetString("Currency_ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Rupee.
        /// </summary>
        internal static string Currency_INR {
            get {
                return ResourceManager.GetString("Currency_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraqi Dinar.
        /// </summary>
        internal static string Currency_IQD {
            get {
                return ResourceManager.GetString("Currency_IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran Rial.
        /// </summary>
        internal static string Currency_IRR {
            get {
                return ResourceManager.GetString("Currency_IRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland Krona.
        /// </summary>
        internal static string Currency_ISK {
            get {
                return ResourceManager.GetString("Currency_ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaican Dollar.
        /// </summary>
        internal static string Currency_JMD {
            get {
                return ResourceManager.GetString("Currency_JMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordanian Dinar.
        /// </summary>
        internal static string Currency_JOD {
            get {
                return ResourceManager.GetString("Currency_JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Yen.
        /// </summary>
        internal static string Currency_JPY {
            get {
                return ResourceManager.GetString("Currency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenyan Shilling.
        /// </summary>
        internal static string Currency_KES {
            get {
                return ResourceManager.GetString("Currency_KES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyzstani Som.
        /// </summary>
        internal static string Currency_KGS {
            get {
                return ResourceManager.GetString("Currency_KGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia Riel.
        /// </summary>
        internal static string Currency_KHR {
            get {
                return ResourceManager.GetString("Currency_KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comoros Franc.
        /// </summary>
        internal static string Currency_KMF {
            get {
                return ResourceManager.GetString("Currency_KMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Korean Won.
        /// </summary>
        internal static string Currency_KPW {
            get {
                return ResourceManager.GetString("Currency_KPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South-Korean Won.
        /// </summary>
        internal static string Currency_KRW {
            get {
                return ResourceManager.GetString("Currency_KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwaiti Dinar.
        /// </summary>
        internal static string Currency_KWD {
            get {
                return ResourceManager.GetString("Currency_KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cayman Islands Dollar.
        /// </summary>
        internal static string Currency_KYD {
            get {
                return ResourceManager.GetString("Currency_KYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstan Tenge.
        /// </summary>
        internal static string Currency_KZT {
            get {
                return ResourceManager.GetString("Currency_KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao Kip.
        /// </summary>
        internal static string Currency_LAK {
            get {
                return ResourceManager.GetString("Currency_LAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanese Pound.
        /// </summary>
        internal static string Currency_LBP {
            get {
                return ResourceManager.GetString("Currency_LBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lanka Rupee.
        /// </summary>
        internal static string Currency_LKR {
            get {
                return ResourceManager.GetString("Currency_LKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberian Dollar.
        /// </summary>
        internal static string Currency_LRD {
            get {
                return ResourceManager.GetString("Currency_LRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesotho Loti.
        /// </summary>
        internal static string Currency_LSL {
            get {
                return ResourceManager.GetString("Currency_LSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian Litas.
        /// </summary>
        internal static string Currency_LTL {
            get {
                return ResourceManager.GetString("Currency_LTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian Lats.
        /// </summary>
        internal static string Currency_LVL {
            get {
                return ResourceManager.GetString("Currency_LVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libyan Dinar.
        /// </summary>
        internal static string Currency_LYD {
            get {
                return ResourceManager.GetString("Currency_LYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moroccan Dirham.
        /// </summary>
        internal static string Currency_MAD {
            get {
                return ResourceManager.GetString("Currency_MAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldovan Leu.
        /// </summary>
        internal static string Currency_MDL {
            get {
                return ResourceManager.GetString("Currency_MDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malagasy Ariary.
        /// </summary>
        internal static string Currency_MGA {
            get {
                return ResourceManager.GetString("Currency_MGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian Denar.
        /// </summary>
        internal static string Currency_MKD {
            get {
                return ResourceManager.GetString("Currency_MKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myanmar Kyat.
        /// </summary>
        internal static string Currency_MMK {
            get {
                return ResourceManager.GetString("Currency_MMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian Tugrik.
        /// </summary>
        internal static string Currency_MNT {
            get {
                return ResourceManager.GetString("Currency_MNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macau Pataca.
        /// </summary>
        internal static string Currency_MOP {
            get {
                return ResourceManager.GetString("Currency_MOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritania Ougulya.
        /// </summary>
        internal static string Currency_MRO {
            get {
                return ResourceManager.GetString("Currency_MRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritius Rupee.
        /// </summary>
        internal static string Currency_MUR {
            get {
                return ResourceManager.GetString("Currency_MUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldives Rufiyaa.
        /// </summary>
        internal static string Currency_MVR {
            get {
                return ResourceManager.GetString("Currency_MVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawi Kwacha.
        /// </summary>
        internal static string Currency_MWK {
            get {
                return ResourceManager.GetString("Currency_MWK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican Peso.
        /// </summary>
        internal static string Currency_MXN {
            get {
                return ResourceManager.GetString("Currency_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Ringgit.
        /// </summary>
        internal static string Currency_MYR {
            get {
                return ResourceManager.GetString("Currency_MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambican Metical.
        /// </summary>
        internal static string Currency_MZN {
            get {
                return ResourceManager.GetString("Currency_MZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibian Dollar.
        /// </summary>
        internal static string Currency_NAD {
            get {
                return ResourceManager.GetString("Currency_NAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerian Naira.
        /// </summary>
        internal static string Currency_NGN {
            get {
                return ResourceManager.GetString("Currency_NGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaragua Cordoba.
        /// </summary>
        internal static string Currency_NIO {
            get {
                return ResourceManager.GetString("Currency_NIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian Kroner.
        /// </summary>
        internal static string Currency_NOK {
            get {
                return ResourceManager.GetString("Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepalese Rupee.
        /// </summary>
        internal static string Currency_NPR {
            get {
                return ResourceManager.GetString("Currency_NPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand Dollar.
        /// </summary>
        internal static string Currency_NZD {
            get {
                return ResourceManager.GetString("Currency_NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambican Metical.
        /// </summary>
        internal static string Currency_NZN {
            get {
                return ResourceManager.GetString("Currency_NZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omani Rial.
        /// </summary>
        internal static string Currency_OMR {
            get {
                return ResourceManager.GetString("Currency_OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panama Balboa.
        /// </summary>
        internal static string Currency_PAB {
            get {
                return ResourceManager.GetString("Currency_PAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruvian Nuevo Sol.
        /// </summary>
        internal static string Currency_PEN {
            get {
                return ResourceManager.GetString("Currency_PEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua New Guinea Kina.
        /// </summary>
        internal static string Currency_PGK {
            get {
                return ResourceManager.GetString("Currency_PGK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippine Peso.
        /// </summary>
        internal static string Currency_PHP {
            get {
                return ResourceManager.GetString("Currency_PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistani Rupee.
        /// </summary>
        internal static string Currency_PKR {
            get {
                return ResourceManager.GetString("Currency_PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish Zloty.
        /// </summary>
        internal static string Currency_PLN {
            get {
                return ResourceManager.GetString("Currency_PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguayan Guarani.
        /// </summary>
        internal static string Currency_PYG {
            get {
                return ResourceManager.GetString("Currency_PYG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatar Rial.
        /// </summary>
        internal static string Currency_QAR {
            get {
                return ResourceManager.GetString("Currency_QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian New Leu.
        /// </summary>
        internal static string Currency_RON {
            get {
                return ResourceManager.GetString("Currency_RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian Dinar.
        /// </summary>
        internal static string Currency_RSD {
            get {
                return ResourceManager.GetString("Currency_RSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Rouble.
        /// </summary>
        internal static string Currency_RUB {
            get {
                return ResourceManager.GetString("Currency_RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwanda Franc.
        /// </summary>
        internal static string Currency_RWF {
            get {
                return ResourceManager.GetString("Currency_RWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Arabian Riyal.
        /// </summary>
        internal static string Currency_SAR {
            get {
                return ResourceManager.GetString("Currency_SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Islands Dollar.
        /// </summary>
        internal static string Currency_SBD {
            get {
                return ResourceManager.GetString("Currency_SBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychelles Rupee.
        /// </summary>
        internal static string Currency_SCR {
            get {
                return ResourceManager.GetString("Currency_SCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudanese Pound.
        /// </summary>
        internal static string Currency_SDG {
            get {
                return ResourceManager.GetString("Currency_SDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish Krona.
        /// </summary>
        internal static string Currency_SEK {
            get {
                return ResourceManager.GetString("Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore Dollar.
        /// </summary>
        internal static string Currency_SGD {
            get {
                return ResourceManager.GetString("Currency_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St Helena Pound.
        /// </summary>
        internal static string Currency_SHP {
            get {
                return ResourceManager.GetString("Currency_SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian Tolar.
        /// </summary>
        internal static string Currency_SIT {
            get {
                return ResourceManager.GetString("Currency_SIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leone Leone.
        /// </summary>
        internal static string Currency_SLL {
            get {
                return ResourceManager.GetString("Currency_SLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somali Shilling.
        /// </summary>
        internal static string Currency_SOS {
            get {
                return ResourceManager.GetString("Currency_SOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surinamese Dollar.
        /// </summary>
        internal static string Currency_SRD {
            get {
                return ResourceManager.GetString("Currency_SRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao Tome Dobra.
        /// </summary>
        internal static string Currency_STD {
            get {
                return ResourceManager.GetString("Currency_STD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Salvador Colon.
        /// </summary>
        internal static string Currency_SVC {
            get {
                return ResourceManager.GetString("Currency_SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrian Pound.
        /// </summary>
        internal static string Currency_SYP {
            get {
                return ResourceManager.GetString("Currency_SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaziland Lilageni.
        /// </summary>
        internal static string Currency_SZL {
            get {
                return ResourceManager.GetString("Currency_SZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai Baht.
        /// </summary>
        internal static string Currency_THB {
            get {
                return ResourceManager.GetString("Currency_THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajikistani Somoni.
        /// </summary>
        internal static string Currency_TJS {
            get {
                return ResourceManager.GetString("Currency_TJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmenistan Manat.
        /// </summary>
        internal static string Currency_TMT {
            get {
                return ResourceManager.GetString("Currency_TMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisian Dinar.
        /// </summary>
        internal static string Currency_TND {
            get {
                return ResourceManager.GetString("Currency_TND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonga Pa&apos;anga.
        /// </summary>
        internal static string Currency_TOP {
            get {
                return ResourceManager.GetString("Currency_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Turkish Lira.
        /// </summary>
        internal static string Currency_TRY {
            get {
                return ResourceManager.GetString("Currency_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidad&amp;Tobago Dollar.
        /// </summary>
        internal static string Currency_TTD {
            get {
                return ResourceManager.GetString("Currency_TTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Taiwan Dollar.
        /// </summary>
        internal static string Currency_TWD {
            get {
                return ResourceManager.GetString("Currency_TWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzanian Shilling.
        /// </summary>
        internal static string Currency_TZS {
            get {
                return ResourceManager.GetString("Currency_TZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine Hryvnia.
        /// </summary>
        internal static string Currency_UAH {
            get {
                return ResourceManager.GetString("Currency_UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugandan Shilling.
        /// </summary>
        internal static string Currency_UGX {
            get {
                return ResourceManager.GetString("Currency_UGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Dollar.
        /// </summary>
        internal static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguayan New Peso.
        /// </summary>
        internal static string Currency_UYU {
            get {
                return ResourceManager.GetString("Currency_UYU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistani Som.
        /// </summary>
        internal static string Currency_UZS {
            get {
                return ResourceManager.GetString("Currency_UZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuelan Bolivar.
        /// </summary>
        internal static string Currency_VEF {
            get {
                return ResourceManager.GetString("Currency_VEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam Dong.
        /// </summary>
        internal static string Currency_VND {
            get {
                return ResourceManager.GetString("Currency_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanuatu Vatu.
        /// </summary>
        internal static string Currency_VUV {
            get {
                return ResourceManager.GetString("Currency_VUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoa Tala.
        /// </summary>
        internal static string Currency_WST {
            get {
                return ResourceManager.GetString("Currency_WST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFA Franc BEAC.
        /// </summary>
        internal static string Currency_XAF {
            get {
                return ResourceManager.GetString("Currency_XAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Ounces.
        /// </summary>
        internal static string Currency_XAG {
            get {
                return ResourceManager.GetString("Currency_XAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Ounces.
        /// </summary>
        internal static string Currency_XAU {
            get {
                return ResourceManager.GetString("Currency_XAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Caribbean Dollar.
        /// </summary>
        internal static string Currency_XCD {
            get {
                return ResourceManager.GetString("Currency_XCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Drawing Rights.
        /// </summary>
        internal static string Currency_XDR {
            get {
                return ResourceManager.GetString("Currency_XDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFA Franc BCEAO.
        /// </summary>
        internal static string Currency_XOF {
            get {
                return ResourceManager.GetString("Currency_XOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Franc.
        /// </summary>
        internal static string Currency_XPF {
            get {
                return ResourceManager.GetString("Currency_XPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemen Riyal.
        /// </summary>
        internal static string Currency_YER {
            get {
                return ResourceManager.GetString("Currency_YER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South African Rand.
        /// </summary>
        internal static string Currency_ZAR {
            get {
                return ResourceManager.GetString("Currency_ZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambian Kwacha.
        /// </summary>
        internal static string Currency_ZMK {
            get {
                return ResourceManager.GetString("Currency_ZMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambian Kwacha.
        /// </summary>
        internal static string Currency_ZMW {
            get {
                return ResourceManager.GetString("Currency_ZMW", resourceCulture);
            }
        }
    }
}
